package com.ri.orchestrator.model;

public enum ConversationState {
  START,
  CAPTURA_TIPO_CLIENTE,
  CAPTURA_CLIENTE_EXISTENTE,
  CAPTURA_CLIENTE_MANUAL,
  CAPTURA_SUCURSAL,
  CAPTURA_DIRECCION_MANUAL,
  CAPTURA_TRABAJO,
  CAPTURA_MANO_OBRA,
  CAPTURA_MATERIALES_CONFIRM,
  CAPTURA_MATERIALES,
  CAPTURA_EQUIPOS_CONFIRM,
  CAPTURA_EQUIPOS,
  CAPTURA_EXTRAS_CONFIRM,
  CAPTURA_EXTRAS,
  RESUMEN,
  CONFIRMACION,
  SUCCESS,
  ERROR
}
